- name: Install yum packages
  yum: name={{ item }} state=latest
  with_items:
    - mysql-server

- name: Copy my.cnf
  copy: >
    src=etc/my.cnf
    dest=/etc/my.cnf
  notify: Restart mysqld

- name: Restart mysqld
  service: name=mysqld state=started enabled=yes

- name: Create a database
  mysql_db: name={{ db.name }} state=present

- name: Create a user
  mysql_user: >
    name={{ db.user }}
    priv=*.*:ALL
    state=present