site_domain: example.com
project_name: simpledjango
project_root: /home/webapp/{{ project_name }}
db_name: {{ project_name }}
db_user: root
virtualenv_python: /home/webapp/.virtualenvs/{{ project_name }}
deploy_root: /home/webapp/{{ project_name }}
#deploy_repo: git@github.com:itkr/simpledjango.git
deploy_repo: https://github.com/itkr/simpledjango.git
deploy_branch: master
env: production
django_settings: settings.{{ env }}
admin_name: "My Name"
admin_email: mail@example.com