---
#
# 実行例
# ansible-playbook create_user.yml -u root --ask-pass
#
- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
    - vars/global.yml
  vars_prompt:
    - name: user_password
      prompt: "webapp user password"
      private: yes
      confirm: yes
  roles:
    - user