# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-31 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import modules.tools.djangopager.pager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=30)),
                ('url', models.CharField(default=b'', max_length=255)),
                ('link', models.CharField(default=b'', max_length=255)),
                ('description', models.TextField(default=b'', null=True)),
            ],
            bases=(models.Model, modules.tools.djangopager.pager.PagerMixin),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default=b'', max_length=255)),
                ('entry_id', models.CharField(default=b'', max_length=255, unique=True)),
                ('url', models.CharField(default=b'', max_length=255, unique=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(default=b'')),
                ('summary_detail', models.TextField(default=b'')),
            ],
            bases=(models.Model, modules.tools.djangopager.pager.PagerMixin),
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=255)),
                ('entry_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entrytag',
            unique_together=set([('entry_id', 'name')]),
        ),
    ]
