---
yum_packages:
  - zlib-devel
  - bzip2-devel
  - openssl-devel
  - ncurses-devel
  - sqlite-devel
  - readline-devel
  - tk-devel
  - httpd-devel
  - httpd
  - gcc
  - mysql-devel
  - MySQL-python